[package]
name = "pam"
version = "0.1.0"
authors = ["tearne <tearne@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pam = { version = "0.7.0" }
rpassword = "5.0.1"
# pam-client = "0.3.0"
