[package]
name = "vega"
version = "0.1.0"
edition = "2024"

[dependencies]
dialoguer = "0.12.0"
eyre = "0.6.12"
json-pretty-compact = "0.1.2"
log = "0.4.28"
serde = { version = "1.0.225", features = ["derive"] } 
serde_json = "1.0.145"
simple_logger = "5.0.0"
