[package]
name = "cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = "3.2.1"
unicorn = { git = "https://github.com/tearne/unicorn", branch = "main"}
rgb = "0.8"
rand = "0.8.4"
